# Grunt
# Run the Grunt JavaScript task runner
- task: Grunt@0
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship'
    appName: 'amanamarketmf'
    package: '$(System.DefaultWorkingDirectory)'
    gruntFile: 'Gruntfile.js' 
    #targets: # Optional
    #arguments: # Optional
    #workingDirectory: # Optional
    gruntCli: 'node_modules/grunt-cli/bin/grunt' 
    #publishJUnitResults: false # Optional
    testResultsFiles: '**/TEST-*.xml' # Required when publishJUnitResults == True
    #testRunTitle: # Optional
    #enableCodeCoverage: false # Optional
    #testFramework: 'Mocha' # Optional. Options: mocha, jasmine
    #srcFiles: # Optional
    testFiles: 'test/*.js' # Required when enableCodeCoverage == True

    #customWebConfig: '-Handler iisnode -NodeStartFile server.js -appType node'